# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-08 07:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashtag',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='timestamp',
        ),
    ]
