# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-11-08 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('hashtags', '0002_auto_20181108_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='hashtag',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hashtag',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
